### ISSUE TITLE
没触发事件？

### ISSUE THREAD

**Issue by yunzimo** [kukume/kuku-bot#1]
这什么情况啊，发送指令没有反应啊

![image](https://user-images.githubusercontent.com/45143713/88903287-0932db80-d286-11ea-9266-e47910642fa4.png)

**Comment by kukume** [comment]
说明里面写了，先发`机器人 开`才能在该群开启机器人

**Comment by yunzimo** [comment]
> 说明里面写了，先发`机器人 开`才能在该群开启机器人

原来是这样啊😂，没注意这个更新
