### ISSUE TITLE
希望能增加机器人在单位时间内的对指令的响应次数限制

### ISSUE THREAD

**Issue by lkiuyu** [kukume/kuku-bot#10]
希望增加限制，机器人对同一个人单位时间内发出的同一个指令只响应限定的次数，防止群友不停的刷屏，比如问答功能，限制一分钟两次，一个人如果在一分钟内把同一个关键词提出两次以上，则机器人在这一分钟内就不自动回答，其他功能也可以加限制，比如舔狗日记，一个人如果在一分钟内把舔狗日记指令提出两次以上，则机器人在这一分钟内就不自动响应对应的功能

**Comment by kukume** [comment]
机器人主人可发送指令`指令限制 (次数)`，将限制1分钟之内同一qq最多响应xx次
