### ISSUE TITLE
希望集成web接口

### ISSUE THREAD

**Issue by iboy-tech** [kukume/kuku-bot#11]

**Comment by kukume** [comment]
希望web集成哪些功能，列一下

**Comment by iboy-tech** [comment]
可以通过http接口实现向指定群发送消息，就是实现RPC远程给别的项目调用，推送消息

**Comment by kukume** [comment]
下载最新的配置文件，`webServer.port`即为网站端口，默认为8081
私聊消息：http://localhost:8081/privateMessage?qq=xxx&msg=xxx
临时消息：http://localhost:8081/tempMessage?group=xxx&qq=xxx&msg=xxx
群聊消息：http://localhost:8081/groupMessage?group=xxx&msg=xxx

**Comment by iboy-tech** [comment]
post请求行吗

**Comment by kukume** [comment]
> post请求行吗

自己测试，我只测试了get，毕竟框架不是我的

**Comment by iboy-tech** [comment]
新版本的数据库和之前不兼容吗，更新之后之前设置的违禁词没了

**Comment by kukume** [comment]
不兼容，提交记录里面写了

**Comment by iboy-tech** [comment]
换了数据库吗，还是改了字段或者表名啊，这升级的代价有点高了

**Comment by kukume** [comment]
字段和表名都换了
