### ISSUE TITLE
色图获取失败

### ISSUE THREAD

**Issue by Faithhhhh** [kukume/kuku-bot#14]
![0FH0ZY AG N4LG2ICB3@3B9](https://user-images.githubusercontent.com/74066078/98391667-e5a3dc00-2091-11eb-80ce-39faa8185501.png)

**Comment by kukume** [comment]
链接超时了，默认的那个类型被墙了，换lolicon把。不过lolicon有个bug。白天整一下

**Comment by Faithhhhh** [comment]
![image](https://user-images.githubusercontent.com/74066078/98433702-54218200-2104-11eb-9497-ec9af7807144.png)
可以了可以了
