### ISSUE TITLE
不能ping

### ISSUE THREAD

**Issue by mugen-cmd** [kukume/kuku-bot#2]
![Screenshot_20200806_081131_com termux](https://user-images.githubusercontent.com/62331500/89476216-b47aed80-d7bc-11ea-872f-b652e79272ef.jpg)
现在还是不能ping

**Comment by kukume** [comment]
ping我用了一个查ip信息的接口，现在那个接口gg了，所以不能用了

**Comment by kukume** [comment]
不对，没看到异常信息，你试试在命令行termux那个命令行输入ping baidu.com 试试

**Comment by mugen-cmd** [comment]
![Screenshot_20200806_100010_com termux](https://user-images.githubusercontent.com/62331500/89482040-a1234e80-d7cb-11ea-9cc3-f982f67d8b6d.jpg)
你看看

**Comment by kukume** [comment]
你是Termux套Linux运行的把，如果是debian系统，安装一下ping，
```
apt-get install iputils-ping -y
```
centos可能是
```
yum install iputils-ping -y
```

**Comment by kukume** [comment]
安装好了暂时还是不能用，因为我用的那个查IP信息的接口gg了

**Comment by kukume** [comment]
现在接口没问题了
