### ISSUE TITLE
登录不上提示这个，密码没错

### ISSUE THREAD

**Issue by iboy-tech** [kukume/kuku-bot#24]
,	... 7 more
,Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=)
,	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
,	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
,	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
,	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
,	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
,	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
,	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
,	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
,	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
,	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
,	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
,	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
,	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
,	at com.icecreamqaq.yuq.mirai.MiraiBot.init(MiraiBot.kt:145)
,	at com.IceCreamQAQ.Yu.as.AsLoader.load(AsLoader.kt:42)
,	at com.IceCreamQAQ.Yu.loader.AppLoader.load(AppLoader.kt:86)
,	... 8 more
,

**Comment by kukume** [comment]
mirai的问题
建议再能登上的设备备份device.json，再尝试登录

**Comment by iboy-tech** [comment]
之前可以登录上的，也登录不了了

**Comment by iboy-tech** [comment]
有其他解决办法吗

**Comment by kukume** [comment]
建议询问mirai

**Comment by kukume** [comment]
最新版本已支持过滑块验证码（版本过低，环境异常等都是不能过滑块验证码的原因），但是需要gui环境，如果是把挂在无ui环境的，可以在有ui环境（比如：windows系统）的机器上登录成功后，把device.json复制到程序根目录
