### ISSUE TITLE
复读怎么关闭

### ISSUE THREAD

**Issue by 1578339936** [kukume/kuku-bot#25]
复读怎么关闭

**Comment by kukume** [comment]
暂时关不了，我加个开关。

**Comment by 1578339936** [comment]
好的

**Comment by 1578339936** [comment]
那哔哩哔哩相关的功能怎么用的
菜单看不懂
笨了

**Comment by kukume** [comment]
已更新。

**Comment by kukume** [comment]
bllogin qr   扫码登录
哔哩哔哩/add/{type}/{username}     /为空格  type可以为开播提醒、赞、评论、转发、投硬币、收藏    。自动帮你赞动态，评论动态、转发动态、投硬币动态、收藏动态
哔哩哔哩/del/{type}/{username}
哔哩哔哩/list/{type}
哔哩哔哩关注监控 {status}    开启之后  你关注的用户有新动态会提示你
哔哩哔哩任务 {status}   开启之后  每天会帮你自动完成经验任务
哔哩哔哩举报 {bvId}    举报一个视频下面的所有评论

**Comment by 1578339936** [comment]
咋关啊。。指令是什么

**Comment by kukume** [comment]
复读 关

**Comment by 1578339936** [comment]
看到了

**Comment by 1578339936** [comment]
- 

1. 
![QQ截图20201230233802](https://user-images.githubusercontent.com/62222561/103364209-20f1e280-4af8-11eb-9f7b-e460ea9f72c3.jpg)

。。。

**Comment by kukume** [comment]
出异常了吗？

**Comment by kukume** [comment]
修复了。编译包下载：https://file.kuku.me  去这里下载编译包或者使用docker更新
