### ISSUE TITLE
Mirai-Console版似乎不支持最新的2.0-RC？

### ISSUE THREAD

**Issue by Cubik65536** [kukume/kuku-bot#27]
在一个全新的环境里安装了Mirai-Console和kuku-bot，可是通过mcl启动之后该插件并未被加载。
### OS：
CentOS 7 x86_64

### Java：
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

**Comment by Cubik65536** [comment]
我最开始时在GitHub Releases处下载的，随后我尝试了README中出现的链接提供的最新版本（2020-01-12），但是启动时仍然没有识别到kukubot，jar包已经放在mcl/plugins目录下了

**Comment by kukume** [comment]
这个不是mirai-console版本，直接通过java -jar可以启动，
https://www.kuku.me/archives/6/   这里有教程。
我不喜欢mirai-console的指令操作，觉得不好用，移植过后就没有更新过了

**Comment by Cubik65536** [comment]
明白了，谢谢！
