### ISSUE TITLE
腾讯的ai开放平台服务调整了

### ISSUE THREAD

**Issue by lkiuyu** [kukume/kuku-bot#30]
目前新创建的应用已经不能加入图片鉴黄和通用ocr的能力了，只有智能闲聊还能添加

**Comment by kukume** [comment]
将会加入百度ai，但是百度ai会有一个免费额度，超过收费

**Comment by kukume** [comment]
语音识别：https://ai.baidu.com/tech/speech  指令：baiduai speech
OCR：https://ai.baidu.com/tech/ocr/general  指令：baiduai ocr
鉴黄：https://ai.baidu.com/solution/censoring 指令：baiduai contentCensor
指令均为私聊，需appid，appkey，secretkey，绑定了百度和QQ的优先使用百度ai
