### ISSUE TITLE
Android用户启动CentOS失败

### ISSUE THREAD

**Issue by 448808614** [kukume/kuku-bot#34]
$ cd ~/Termux-Linux/CentOS
$ ./start-centos.sh
proot error: '/data/data/com.termux/files/home/Termux-Linux/CentOS/centos-fs/usr/bin/env' is a 64-bit program whereas this version of proot handles 32-bit programs only
proot info: vpid 1: terminated with signal 11
$

**Comment by kukume** [comment]
在Termux中启动Centos是引用https://www.sqlsec.com/2020/04/termuxlinux.html
这个大佬的教程，建议去他博客底下反馈

**Comment by 448808614** [comment]
别人问过了，没有回答

**Comment by kukume** [comment]
那可以试试其他系统。我在安卓10上使用Debian系统没有问题
