### ISSUE TITLE
大佬，有考虑支持ipv6吗

### ISSUE THREAD

**Issue by lkiuyu** [kukume/kuku-bot#35]
薅了一台euserv的纯ipv6机子没ipv4的地址，发现运行机器人后机器人登陆不了账号，貌似是因为用的dns64只能解析ipv4的域名，但ipv4的地址不能解析，大佬你看有什么解决方案吗

**Comment by kukume** [comment]
机器人跟腾讯交互（登录/发送消息等）的核心是由mirai提供的。所以我无法解决这个问题
