### ISSUE TITLE
哔哩哔哩监控能否增加显示分享者分享的内容

### ISSUE THREAD

**Issue by 742903746** [kukume/kuku-bot#4]
目前分享者分享了一个帖子或视频推送的的QQ群的信息是这样子的
内容：没有发现内容！！

**Comment by kukume** [comment]
如果该动态是转发的话，下面应该会有转发自，然后就是该动态转发的内容，如果没有的话，提供一下这个用户名

**Comment by 742903746** [comment]
@kukume 
好像是发的专栏吧。对了，能不能增加一个随机色图？链接：https://api.lolicon.app/#/

SCP基金会中国
发布时间：2020-09-04 18:39:36
内容：没有发现内容！！
动态链接：https://t.bilibili.com/431118406174418869
视频链接：没有发现视频
薇尔莉特-伊芙加登丿

发布时间：2020-09-04 18:46:12
内容：没有发现内容！！
动态链接：https://t.bilibili.com/431120106983578448
视频链接：没有发现视频

**Comment by kukume** [comment]
随机色图功能有，发送涩图/色图就行了，
动态我等会适配一下

**Comment by 742903746** [comment]
@kukume 在一个QQ群看到别人发的html文件。

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>随机色图显示器</title>
<script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js">
</script>
<script>
$(document).ready(function(){
	$.ajax({
		type:"get",
		dataType:"json",
		url:"https://api.lolicon.app/setu/?r18=1",
		success: function (data){
			var setu=data.data;
			$('#r18').attr('src', setu[0].url);
		}
	})
})	
</script>
</head>

<body>
<img id="r18" src=""/>
</body>
</html>

**Comment by kukume** [comment]
需要r18的话，指令`涩图切换 r-18`，这个api有调用次数的限制，我不喜欢，我自己提供了一个色图api来发送随机色图

**Comment by 742903746** [comment]
@kukume 机器人带的那个涩图发的图很多画风不太好看，建议加入这个功能然后让机器人主人可以自定义配置key

**Comment by 742903746** [comment]
@kukume 两个随机图都保留，用不同的命令调用

**Comment by kukume** [comment]
我的想法是   加一个涩图切换成这个lolicon

**Comment by kukume** [comment]
7ff03c3
