### ISSUE TITLE
私聊无法设置设置qqai

### ISSUE THREAD

**Issue by 742903746** [kukume/kuku-bot#6]

**Comment by kukume** [comment]
可以前往控制台查看有没有你发送的那条消息的日志，如果没有的话，重启即可。

**Comment by 742903746** [comment]
真的是这问题，谢谢！

**Comment by 742903746** [comment]
@kukume 没有个问题。复读太频繁了，有时候才隔两条消息就复读。

**Comment by kukume** [comment]
我逻辑应该是没问题的，我尝试添加一个锁试试

**Comment by leeyiding** [comment]
> 可以前往控制台查看有没有你发送的那条消息的日志，如果没有的话，重启即可。

私聊机器人发送 "设置 qqAI"  机器人没有反应 控制台有输出
2020-09-05 20:58:48,193 INFO  c.i.y.RainBot@[DefaultDispatcher-worker-2] - ***********) -> ([ "设 置  qqAI" ])
重启机器人还什么没反应

**Comment by kukume** [comment]
> > 可以前往控制台查看有没有你发送的那条消息的日志，如果没有的话，重启即可。
> 
> 私聊机器人发送 "设置 qqAI" 机器人没有反应 控制台有输出
> 2020-09-05 20:58:48,193 INFO c.i.y.RainBot@[DefaultDispatcher-worker-2] - ***********) -> ([ "设 置 qqAI" ])
> 重启机器人还什么没反应

`设置qqAI`，不要分开

**Comment by leeyiding** [comment]
。

> > > 可以前往控制台查看有没有你发送的那条消息的日志，如果没有的话，重启即可。
> > 
> > 
> > 私聊机器人发送 "设置 qqAI" 机器人没有反应 控制台有输出
> > 2020-09-05 20:58:48,193 INFO c.i.y.RainBot@[DefaultDispatcher-worker-2] - ***********) -> ([ "设 置 qqAI" ])
> > 重启机器人还什么没反应
> 
> `设置qqAI`，不要分开

感谢回复 已解决👍

**Comment by 742903746** [comment]
@kukume 大佬中午好！又发现了个问题。我打算保存机器人发的图的时候有注意到都不是原图，能改成发原图吗？(*/ω＼*)

**Comment by 742903746** [comment]
奇怪，怎么我不能像你们一样回复:cry:

**Comment by kukume** [comment]
发送图片的方法就只有一个api，没有区别是不是原图，应该是原图的

**Comment by 742903746** [comment]
@kukume 这还真是！在QQ内是非常模糊的，但是保存到本地就清晰了，这可能是QQ的问题吧。谢谢大佬！

**Comment by 742903746** [comment]
@kukume B站关注动态监控还能降低延迟么？

**Comment by kukume** [comment]
目前是一分钟检测一次  有没有更新的。。
还要降低？
对了。复读还有问题吗

**Comment by 742903746** [comment]
@kukume 被踢了😂

**Comment by kukume** [comment]
复读应该没问题了。。。
