### ISSUE TITLE
【功能建议】查知乎

### ISSUE THREAD

**Issue by leeyiding** [kukume/kuku-bot#7]
建议加一个查知乎的功能
"https://www.zhihu.com/search?q=干货&type=content"
如果能显示出几条前排问答的链接更好

**Comment by kukume** [comment]
看了一下，这个内容也太长了吧，只发链接的话感觉没意义

**Comment by 742903746** [comment]
@kukume  嗨，你能做个哔哩哔哩聊天机器人吗:grinning:

**Comment by kukume** [comment]
> @kukume 嗨，你能做个哔哩哔哩聊天机器人吗😀

不一样的问题新开一个is好吗。还有，具体说清楚这个东西是什么
