### ISSUE TITLE
不能查哔哩哔哩监控了

### ISSUE THREAD

**Issue by 742903746** [kukume/kuku-bot#9]
还有指令菜单也建议更新一下

**Comment by kukume** [comment]
![Screenshot_20201002_160429](https://user-images.githubusercontent.com/45278810/94901286-009a9380-04c9-11eb-81fc-6c4a7a0d50b7.jpg)
我这里测试是没问题的

**Comment by 742903746** [comment]
@kukume [https://cdn.jsdelivr.net/gh/amilys/PicUrl@latest/2020/10/06/ff07b42a3eb956dec46641e98df15151.png](url) [https://cdn.jsdelivr.net/gh/amilys/PicUrl@latest/2020/10/06/a81f4a1f1969b27e9334d1d3b73a502d.png](url) 这是个什么情况？

**Comment by 742903746** [comment]
@kukume  好的，有时不行有时可以。突发奇想，能不能整个自动点赞某用户所有动态功能？也包括之后发布的内容。

**Comment by kukume** [comment]
自动赞新的动态   现在就有

**Comment by kukume** [comment]
`点赞某用户所有动态功能`已更新！！
